"""baseline schema

Revision ID: 64c28a528e54
Revises:
Create Date: 2026-08-02 10:38:33.167710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models

# revision identifiers, used by Alembic.
revision: str = "64c28a528e54"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("channel_name", sa.String(), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    op.create_table(
        "workspace_records",
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("workspace_name", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column("deleted_at", app.models.UTCDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("workspace_id"),
    )
    op.create_table(
        "workspaces",
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("workspace_name", sa.String(), nullable=False),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("default_channel_id", sa.String(), nullable=True),
        sa.Column("created_at", app.models.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_channel_id"],
            ["channels.channel_id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id"),
    )
    op.create_table(
        "members",
        sa.Column("member_id", sa.String(), nullable=False),
        sa.Column("member_name", sa.String(), nullable=False),
        sa.Column("member_type", sa.String(), nullable=False),
        sa.Column("api_key_hash", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("occupation", sa.String(), nullable=True),
        sa.Column("job_role", sa.String(), nullable=True),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("member_id"),
        sa.UniqueConstraint("workspace_id", "email", name="uq_members_workspace_email"),
    )
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_members_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_members_member_name"), ["member_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_members_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "channel_members",
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("member_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.channel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.member_id"],
        ),
        sa.PrimaryKeyConstraint("channel_id", "member_id"),
    )
    op.create_table(
        "messages",
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("sender_member_id", sa.String(), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.channel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_member_id"],
            ["members.member_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
        sa.UniqueConstraint("channel_id", "seq", name="uq_messages_channel_seq"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_channel_seq", ["channel_id", "seq"], unique=False
        )

    op.create_table(
        "refresh_tokens",
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("member_id", sa.String(), nullable=False),
        sa.Column("expires_at", app.models.UTCDateTime(timezone=True), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.member_id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_member_id"), ["member_id"], unique=False
        )

    op.create_table(
        "workspace_invites",
        sa.Column("invite_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("invite_type", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", app.models.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["members.member_id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("invite_id"),
    )
    with op.batch_alter_table("workspace_invites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workspace_invites_code"), ["code"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_workspace_invites_email"), ["email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workspace_invites_workspace_id"),
            ["workspace_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspace_invites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspace_invites_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_workspace_invites_email"))
        batch_op.drop_index(batch_op.f("ix_workspace_invites_code"))

    op.drop_table("workspace_invites")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_member_id"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_channel_seq")

    op.drop_table("messages")
    op.drop_table("channel_members")
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_members_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_members_member_name"))
        batch_op.drop_index(batch_op.f("ix_members_email"))

    op.drop_table("members")
    op.drop_table("workspaces")
    op.drop_table("workspace_records")
    op.drop_table("channels")
    # ### end Alembic commands ###
