import os
import sys
from logging.config import fileConfig
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Repo root on sys.path so `from app.models import Base` resolves when
# alembic runs from the CLI (its working directory is not import-aware
# the way `python -m` invocations are).
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.models import Base  # noqa: E402

load_dotenv()

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

if config.get_main_option("sqlalchemy.url", None) in (None, ""):
    config.set_main_option(
        "sqlalchemy.url", os.getenv("DATABASE_URL", "sqlite:///./smac.db")
    )

# add your model's MetaData object here
# for 'autogenerate' support
target_metadata = Base.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def render_item(type_, obj, autogen_context):  # type: ignore[no-untyped-def]
    """Make autogenerated revisions import our custom column types.

    Every table uses app.models.UTCDateTime; without this hook,
    --autogenerate emits revisions that reference it unimported and
    explode at upgrade time.
    """
    if type_ == "type" and obj.__class__.__module__.startswith("app."):
        autogen_context.imports.add("import app.models")
        return f"app.models.{obj.__class__.__name__}()"
    return False


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        render_item=render_item,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    # Deliberately a bare `engine_from_config` engine -- it never receives
    # the `enable_sqlite_foreign_keys` listener that `app/database.py`
    # attaches to the app's engine, so migrations run with
    # `PRAGMA foreign_keys` OFF. This is load-bearing: SQLite batch-mode
    # migrations (e.g. `alter_column`/`create_unique_constraint` on
    # `members`) recreate the table via copy/drop/rename, and that drop
    # would fail under FK enforcement on any populated DB, since
    # messages/channel_members/refresh_tokens/workspace_invites/mentions
    # all parent to `members`. Do not "fix" this to match runtime FK
    # enforcement without first making batch migrations FK-safe.
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
            render_item=render_item,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
